# Find the Most Frequent Words in a String

def find_kmer(text, k):
    dic = {}
    for i in range(len(text)-k+1):
        kmer = text[i:i+k]
        if kmer in dic:
            dic[kmer] += 1
        else:
            dic[kmer] = 1
    return dic    

dna_text = "AAATGTGTACCCATTAGACCCATTAGAAATGTGTACCCATTAGACCCATTAGTGATGATTGATGATAACAGCGGAAATGTGTACCCATTAGACCCATTAGTGATGATTGATGATAACAGCGGAACAGCGGCCGCGGGAACAGCGGTGATGATAAATGTGTCCGCGGGACCCATTAGAACAGCGGTGATGATAAATGTGTACCCATTAGAACAGCGGACCCATTAGACCCATTAGAACAGCGGTGATGATAAATGTGTACCCATTAGCCGCGGGTGATGATTGATGATTGATGATAACAGCGGAAATGTGTAAATGTGTAAATGTGTAAATGTGTAAATGTGTTGATGATAACAGCGGTGATGATCCGCGGGAACAGCGGTGATGATTGATGATCCGCGGGCCGCGGGTGATGATACCCATTAGTGATGATAAATGTGTACCCATTAGTGATGATAACAGCGGAACAGCGGAAATGTGTACCCATTAGAAATGTGTACCCATTAGACCCATTAGAACAGCGGAAATGTGTTGATGATAACAGCGGAAATGTGTTGATGATTGATGATCCGCGGGTGATGATAACAGCGGAAATGTGTCCGCGGGTGATGATACCCATTAGCCGCGGGCCGCGGGTGATGATACCCATTAGAACAGCGGTGATGATACCCATTAGAACAGCGGCCGCGGGAAATGTGTCCGCGGGAAATGTGTCCGCGGGTGATGATAACAGCGGCCGCGGGCCGCGGGAACAGCGGCCGCGGGAACAGCGGTGATGATTGATGATAAATGTGTAAATGTGT"
k = 13

kmerdic = find_kmer(dna_text, k)

# sort and print most frequent kmer(s)
max_kmers = [key for key, values in kmerdic.items() if values == max(kmerdic.values())]
print(" ".join(max_kmers))





"""
# Counter module, brief version
from collections import Counter

def find_kmer(text, k):
    return Counter(text[i:i+k] for i in range(len(text) - k + 1))

"""